# Generated by Django 5.0.6 on 2024-05-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rooms',
            new_name='Room',
        ),
    ]
